### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by dereke620** [NetAppDocs/netapp-solutions#162]
Page: [Configuring the virtualization environment in the cloud provider](https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-config-vmware.html)

The links on this page are all broken and provider current 404 errors.

**Comment by kevin-hoke** [comment]
Thanks for the find @dereke620 ... missed some updates in a consolidation and will get them fixed ASAP

**Comment by kevin-hoke** [comment]
This issue should be resolved.  I will close this issue unless I hear there are more issues.

**Comment by kevin-hoke** [comment]
Verified links are working.

**Comment by dereke620** [comment]
Hey Kevin,

I see most of the links have been fixed, thank you.

However, I am still getting 404 errors on some of the links here - https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-datastore.html

Specifically any of the "Guest Connected Storage" links.

Thanks,
--

Derek Elbert

Technical Solutions Architect | Cloud Data Management

World Wide Technology

1 World Wide Way | St. Louis, MO 63146

(435) 890-4545

[A picture containing text  Description automatically generated]

[cid:5bf15e0f-561b-4ebd-b19f-c292d80767fb]<https://www.credly.com/badges/a0547236-04d2-4c0d-a610-cd08791c9287/public_url>[cid:5cc9104b-69bc-4983-a679-af0cbc2af063]<https://www.credly.com/badges/b13b71ab-fa0f-44f7-9405-5e626acdce35/public_url>[cid:c94885f4-76c6-4be0-9461-3798710ca4d9]<https://www.credly.com/badges/cf952b7f-3b5e-4486-95f8-28f14343cf55/public_url>[cid:4a890915-a375-4aa1-b658-1e772847dda4]<https://www.credly.com/badges/214e5707-f97e-4195-beae-069dc5a7b162/public_url>​[cid:47ae1c99-6efa-4df1-bf8a-7cdb3631ea26]<https://www.credly.com/badges/104e49b4-6f3e-4124-b279-d22d1b98bf51/public_url>
[cid:b3171a83-6b7e-4762-b978-3d0197027283]<https://www.credly.com/badges/8969c9fb-f518-4286-9a92-80995c26521e/public_url>[cid:07affc59-d077-40be-ac17-b9f08428786a]<https://www.credly.com/badges/36fdc2da-f9ee-43b7-a5fe-59f0cf612913/public_url>

________________________________

**Comment by kevin-hoke** [comment]
Hey Derek,

Thanks for the response.  It looks like we missed an update from the consolidation and this will be fixed in an hour or so.  Thanks again for reporting the issues.

Thanks,
Kevin

On 12/23/21, 12:41 PM, "dereke620" ***@***.***> wrote:

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hey Kevin,

I see most of the links have been fixed, thank you.

However, I am still getting 404 errors on some of the links here - https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-datastore.html

Specifically any of the "Guest Connected Storage" links.

Thanks,
--

Derek Elbert

Technical Solutions Architect | Cloud Data Management

World Wide Technology

1 World Wide Way | St. Louis, MO 63146

(435) 890-4545

[A picture containing text Description automatically generated]

[cid:5bf15e0f-561b-4ebd-b19f-c292d80767fb]<https://www.credly.com/badges/a0547236-04d2-4c0d-a610-cd08791c9287/public_url>[cid:5cc9104b-69bc-4983-a679-af0cbc2af063]<https://www.credly.com/badges/b13b71ab-fa0f-44f7-9405-5e626acdce35/public_url>[cid:c94885f4-76c6-4be0-9461-3798710ca4d9]<https://www.credly.com/badges/cf952b7f-3b5e-4486-95f8-28f14343cf55/public_url>[cid:4a890915-a375-4aa1-b658-1e772847dda4]<https://www.credly.com/badges/214e5707-f97e-4195-beae-069dc5a7b162/public_url>​[cid:47ae1c99-6efa-4df1-bf8a-7cdb3631ea26]<https://www.credly.com/badges/104e49b4-6f3e-4124-b279-d22d1b98bf51/public_url>
[cid:b3171a83-6b7e-4762-b978-3d0197027283]<https://www.credly.com/badges/8969c9fb-f518-4286-9a92-80995c26521e/public_url>[cid:07affc59-d077-40be-ac17-b9f08428786a]<https://www.credly.com/badges/36fdc2da-f9ee-43b7-a5fe-59f0cf612913/public_url>

________________________________

**Comment by dereke620** [comment]
Perfect! Thanks again Kevin and have a happy holiday!

Thanks,

Derek Elbert
Sent from Outlook iOS
________________________________
